---
# tasks file for apache_php
  - name: Import os specific variables
    import_vars: "{{ ansible_os_family }}.yml"

  - name: Create apache group
    group:
      name: "{{ apache_group }}"
      gid: 501
      system: yes
      state: present
  
  - name: Create apache user
    user:
      name: "{{ apache_user }}"
      comment: Apache admin user
      uid: 501
      group: "{{ apache_group }}"
      system: yes
      state: present